### ISSUE TITLE
Empty query should produce one param

### ISSUE THREAD

**Issue by robhobbes** [boostorg/url#129]
I parsed `http://examplebucket.s3.amazonaws.com/test.txt` with `url_view uv = parse_uri(url).value();`. As expected, `uv.has_query()` is false and `uv.encoded_params().size()` is 0. However, a loop (`for (auto p : uv.encoded_params())`) does execute one time.

I'm on commit `8911d05c35123f978e90321fea863385b63525d4`

Here's my example program using gtest:
```
#include <gtest/gtest.h>
#include <boost/url.hpp>

#include <sstream>
#include <string>

namespace {

using namespace boost::urls;
using std::string;

TEST(UrlQueryParsing,CheckQueryParams)
{
    string url = "http://examplebucket.s3.amazonaws.com/test.txt";
    url_view uv = parse_uri(url).value();
    std::cout << "Has query: " << uv.has_query() << ", Size: " << uv.encoded_params().size() << std::endl;
    std::stringstream ss;
    for (auto p : uv.encoded_params()) {
        std::cout << "Key: " << p.key << ", Value: " << p.value << std::endl;
        ss << "Key: " << p.key << ", Value: " << p.value << std::endl;
    }
    EXPECT_EQ(ss.str(), string(""));
}

}
```

Output:
```
Has query: 0, Size: 0
Key: , Value:
tests/url_query_parsing.cpp:22: Failure
Expected equality of these values:
  ss.str()
    Which is: "Key: , Value: \n"
  string("")
    Which is: ""
```

**Comment by vinniefalco** [comment]
darnit... you're right - that's not supposed to happen !!!!!!!!

**Comment by vinniefalco** [comment]
This is because, in the URL `http://example.com/index.htm?` there is one query param whose key and value are empty. So the code handles this case. However, the caller has to check that the size of the params container is not zero, as otherwise there is no way to tell if an empty string represents a non-existing query (size==0) or a query with one empty param (size==1).

In other words, it was a bug :) Thanks for reporting this, these containers were a chore to get right.

**Comment by vinniefalco** [comment]
should be fixed in master/develop now

**Comment by vinniefalco** [comment]
Unfortunately this was resolved incorrectly. The relative-ref `"?"` should produce exactly one query parameter, with an empty key and no value. Otherwise, if it was to produce zero parameters, then it would not be distinguishable from the relative-ref `""` and round-trips would be lossy.

**Comment by vinniefalco** [comment]
`url_view( "?" )` produces one key/value pair with an empty key and no value

while `parse_params( "" )` produces no key/value pairs
