### ISSUE TITLE
Check Help Card against actual declaration

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#259]
The contents of the Help Card need to be checked against the `url` and `url_view` declarations to ensure that the members are accurate.

**Comment by alandefreitas** [comment]
I went through the help card and:

- `set_scheme_id` should be removed (when did that happen? is that on purpose?)
- `ipv_future` should become `ipvfuture` or vice-versa. Which one do we want?

Is that correct?

**Comment by vinniefalco** [comment]
I guessed `set_scheme_id` but I was wrong, it is `set_scheme` with 2 overloads. But I wonder if we should rename it... the docs kind of suffer a little bit because of it. `set_scheme_id` is more discoverable.

`ipvfuture` is correct.

**Comment by vinniefalco** [comment]
We should remove `set_scheme_id`, but we should open an issue to start a discussion on if we should rename it to `set_scheme_id` in the API. This would have to wait until after the review of course.

**Comment by alandefreitas** [comment]
> I guessed set_scheme_id but I was wrong, it is set_scheme with 2 overloads. 

Yes. I agree. I like `set_scheme` with two overloads more.

> We should remove set_scheme_id, but we should open an issue to start a discussion on if we should rename it to set_scheme_id in the API. This would have to wait until after the review of course.

Sure.

**Comment by vinniefalco** [comment]
so you prefer
```
set_scheme( string_view )
set_scheme( scheme )
```

instead of
```
set_scheme( string_view )
set_scheme_id( scheme )
```
?

**Comment by alandefreitas** [comment]
Yes

**Comment by vinniefalco** [comment]
Needs another quick look just to be sure

**Comment by alandefreitas** [comment]
Yes. I've been purposefully ignoring this for now because we're changing a lot lately.

**Comment by alandefreitas** [comment]
This has been done many times since this original issue was opened.
