### ISSUE TITLE
params::set

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#412]
We need
```
std::size_t params::set( string_view key, string_view value );
```

Or even a variadic version
```
template<class... StringViews>
std::size_t params::set( string_view key, string_view value, StringViews... values );
```

However we need to decide what to do with existing matching keys. Should we delete them all first? Only replace the first one? Replace each existing in the variadic case, and switch to appending when needed?

We might also consider having `set_all`  and `set_one` (or just `set`) which appropriate corresponding behaviors.

**Comment by vinniefalco** [comment]
Peter: erase all previous matches, don't bother with variadic

**Comment by vinniefalco** [comment]
`std::initializer_list< string_view >` instead of variadic could be a possibility

**Comment by alandefreitas** [comment]
Something like `?q=[1,2]` is equivalent to `?q=1&q=2`

In URI.js, this would be something like

```
set("q", {"1", "2"})
```

We could add an overload if there is sufficient... _clamour_

**Comment by anarthal** [comment]
I'm with Peter.

**Comment by alandefreitas** [comment]
Quoting the review (for reference)

> Something I've found when playing with mutating URLs is that modifying
a query parameter to a certain value is a little bit verbose:

```cpp
url u; // get it from somewhere
auto it = u.params().find("k");
if (it == u.params().end())
{
    u.params().append("k", "value");
}
else
{
    u.params().replace_value(it, "value");
}
```

> I had this use case in the last web application I wrote (although it
wasn't C++).
I don't know if this is a common use case, but I'd consider adding a function
that simplifies it (i.e. params::set_value(string_view key, string_view value).

**Comment by vinniefalco** [comment]
This is done
