### ISSUE TITLE
Review: parse_uri lifetime issue

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/url#435]
>   auto r = parse_uri( s );
> 
> There's no indication here that r is a non-owning view and that
> the caller is responsible for keeping s alive for the lifetime of r.

> A safer API design would, at a minimum, give the parsing function
> a name with "view" in it. The default, shorter-named function
> should return a value type.

Some solutions would be:

```cpp
auto r = parse_uri_view( s );
```

The biggest problem is deciding what 

```cpp
auto r = parse_uri( s );
```

should return. The non-ambiguous solution would be

```cpp
url u;
auto r = parse_uri( s, u );
```

or a static member function forcing the user to type the type:

```cpp
auto r = url::parse_uri( s );
```

The solution `std::ranges` uses is the `views` namespace, which would be:

```cpp
auto r = urls::views::parse_uri( s );
```

**Comment by alandefreitas** [comment]
I just noticed about another problem with `parse_uri_view(...)` or whatever. It makes it less convenient and doesn't solve much because it just pushes the problem deeper when we access the URL components.

To completely achieve the requirement in the review of `auto x = ...` not tricking "beginners" we would need some kind of:

```cpp
url u = parse_uri(...);
std::string h = u.host();
```

so the user can

```cpp
url u = parse_uri(...);
auto h = u.host();
```

to keep "beginners" from the lifetime issues when using `auto`, which was the original requirement. 

Then we would still need the views for "non-beginners", and this would become lots of variants:

```cpp
std::string h1 = u.host();
std::string h2 = u.encoded_host();
pct_encoded_string h3 = u.host_view();
string_view h4 = u.encoded_host_view();
```

I foresee these extra functions annoying most of the "non-beginners".

**Comment by alandefreitas** [comment]
More comments

> Overall, I quite like the design.  Lazy, lazy, lazy.  The fact that
only views into the underlying sequence are returned from the parse is
great, and the fact that there are both owning (url::url and
fixed-capcity owning url::static_url) and view versions of the URL
representations is exactly what I would need as a user.

**Comment by alandefreitas** [comment]
More comments:

> Overall, I found the API fairly easy to use. I understand the concern about
> parsing into a view type, but I consider it a lesser evil than allocating on
> every parse or creating two kinds of functions, one that allocates and one that
> doesn't.

**Comment by alandefreitas** [comment]
More comments:

> I feel that maybe what I'm saying is not getting through:
> 
> *I am not insisting that you remove these dangerous functions. You
> are welcome to keep them for those users who feel that they need the
> benefits that they offer. I would just like you to *also* offer
> safe-to-use functions, and to give the safe functions more concise
> names than the dangerous functions (and mention them first in the
> docs).*

**Comment by alandefreitas** [comment]
> A good API should use std::string_view only for parameters, and
> possibly for getter methods.

Why would getter methods be OK?

**Comment by alandefreitas** [comment]
Just had a look at [QUrl](https://doc.qt.io/qt-6/qurl.html) and the equivalent member functions would be something like

```cpp
std::string url_view_base::host(pct_decode_opts opts = {}) const;
```

**Comment by alandefreitas** [comment]
> To me the problem is auto. In other words, the issue described here is not specific to URLs; it is general for any user that uses auto to capture the result of a function that returns a reference-like type over its arguments.

Phil made a good point about `auto` and references vs. types acting as references, as references with `auto` are not ambiguous:

```cpp
std::string& get_string();
std::string_view get_string_view();

// ...

auto s0 = get_string(); // value type
auto& s1 = get_string(); // reference type
auto s2 = get_string_view(); // acts as reference type
auto& s3 = get_string_view(); // acts as reference to reference type
```

**Comment by vinniefalco** [comment]
That last line won't compile as you cannot assign an rvalue to a non-const reference

**Comment by alandefreitas** [comment]
Yes. It's even worse.

**Comment by alandefreitas** [comment]
> One cool idea that I like is what abseil does in some cases, they return
> you some "proxy" that morphs into what you specify as lhs. For example
> absl::StrSplit()
>   https://abseil.io/docs/cpp/guides/strings
> 
> Not sure if that design has some problems beside being auto hostile.
> 

This looks a lot like what we already have though.

**Comment by alandefreitas** [comment]
> I see url_view not as a view but as a universal
> type for cheaply constructing different containers storing URLs. Of course,
> this approach is incompatible with the "almost always auto" philosophy,
> which some people now promote to simply "always auto". My personal opinion
> is that this AAA philosophy is harmful from the outset and it begs for
> problems and bugs. If someone adapts the AAA one must accept the
> responsibility for the problems like the one with dangling references.

**Comment by alandefreitas** [comment]
#400

**Comment by vinniefalco** [comment]
Yes this seems like an `auto` problem and not a function name problem

**Comment by alandefreitas** [comment]
One function that could exist is:

```cpp
auto v = parse_uri("http://www.boost.org");
auto u = make_uri("http://www.boost.org");
```

I don't know if this would satisfy the reviewer though.

**Comment by vinniefalco** [comment]
What's the difference here? would we have both? or just the new one?

**Comment by alandefreitas** [comment]
We would have both, to construct url views and urls. 

The only purpose would be to satisfy the reviewer. I don't think I would use these functions myself. 

I'm not even sure this would really satisfy the reviewer, since they might say `parse_uri` is still "confusing". (I'm quoting. I don't find it confusing.)

I'm just mentioning an alternative. But I think I would just wait for people to complain and propose ideas.
