### ISSUE TITLE
Fix pointer UB

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/url#461]
https://github.com/CPPAlliance/url/blob/develop/include/boost/url/detail/impl/any_query_iter.ipp#L299

is undefined behavior because that compares pointers that aren't guaranteed to belong to the same buffer

We need to use `std::less` here.

**Comment by alandefreitas** [comment]
we need a function like this
https://github.com/CPPAlliance/url/blob/develop/include/boost/url/grammar/detail/impl/copied_strings.ipp#L23

```cpp
bool is_overlapping(string_view s, char const* begin, char const* end) noexcept;
```

**Comment by vinniefalco** [comment]
I thought I had it

**Comment by vinniefalco** [comment]
https://github.com/boostorg/url/blob/81cb06ec5e616d609ac01ef1b6a5d67eaa8448e2/include/boost/url/detail/move_chars.hpp#L28
