### ISSUE TITLE
test nulls and escaped nulls in encoded strings

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#471]
Like the params and segments, but also everything else

**Comment by alandefreitas** [comment]
Do you have an example of that?

**Comment by vinniefalco** [comment]
We just need to make sure the library does the right thing when presented with a null percent-escape in a function like `set_encoded_X` (or the params/segments refs) and what do to with a null in a decoded string, e.g. `set_path`

**Comment by alandefreitas** [comment]
> does the right thing

throws an exception?

> presented with a null percent-escape in a function like set_encoded_X 

An encoded `%00` should fail?

> what do to with a null in a decoded string

What should it do? Throw an exception?

**Comment by vinniefalco** [comment]
I don't know! We need to check rfc3986

**Comment by alandefreitas** [comment]
I don't think rfc3986 says anything about decoded `\0`s. This is a reasonable safety issue Peter brought up but URLs are definitely allowed to include encoded `\0`s. The most obvious use case is the `data:` scheme. I think this is up to us because the RFC won't help us here.

**Comment by vinniefalco** [comment]
so then nulls are allowed? check if my unit tests for segments and params tests it
