### ISSUE TITLE
throw system_error

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#473]
When exceptions are thrown due to error codes (`result` or `ec`), we should use `detail::throw_system_error` and ensure the lineage of the source locations traces to the correct places. And we must ensure that every javadoc and noexcept specifier is correct.

**Comment by vinniefalco** [comment]
Also, there should be a unit test for each of these places

**Comment by alandefreitas** [comment]
> the correct places

I think Peter disagrees that these are the correct places. I tend to agree. Not showing the places where it ultimately fails makes it hard to find the problem.

**Comment by vinniefalco** [comment]
Whatever the "correct" place is - I'm saying we should make sure that's what is shown. When system error is thrown there are two locations, one for the error code and the point of assignment and the other for the point of the throw.

**Comment by alandefreitas** [comment]
I couldn't find any `throw_*` that's incorrect. Maybe this has been fixed already?

**Comment by vinniefalco** [comment]
That is possible

**Comment by alandefreitas** [comment]
Could you have a quick look to ensure if that's been already fixed or I didn't understand the problem properly?

**Comment by vinniefalco** [comment]
Yep I will have a look-see

**Comment by vinniefalco** [comment]
This is done, I changed the throw functions so they all throw system error.
