### ISSUE TITLE
"percent-escape", or "percent escape" not both

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#496]

**Comment by alandefreitas** [comment]
I googled that and "percent escape" seems to be more common while "percent-escaped" seems to be more common. :neutral_face: 

On the other hand, [wikipedia](https://en.wikipedia.org/wiki/Percent-encoding) uses hyphens for both.

**Comment by vinniefalco** [comment]
yeah I couldn't come to a conclusion either. I'm not going to worry about it.
