### ISSUE TITLE
tilde is special

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#497]
> The octet corresponding to the tilde ("~") is permitted in query strings by RFC3986 but required to be percent-encoded in HTML forms to "%7E".

This should be added to `encode_opts`

**Comment by alandefreitas** [comment]
How is this different from encoding with the allowed charset `cs - '~'`?

**Comment by vinniefalco** [comment]
maybe it isn't :) less work for us.

**Comment by vinniefalco** [comment]
I think we have a problem with parsing urlencodings which are part of forms anyway.
