### ISSUE TITLE
Remove 1-arg `param` constructor?

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/url#522]
Explore whether `param`s should be implicitly constructible from a single `string_view`. 

One problem with that design is that params has the problem of ambiguity because { "key", "value" } can be either a 2-element list or a 1-element param.

If we thing of params as pairs, we could have something like `{"key", boost::none}`, `{"key", nullptr}` or something.

**Comment by vinniefalco** [comment]
Done. it is `urls::no_value` or `nullptr`
