### ISSUE TITLE
Too much measuring of decoded size

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#529]
`apply_query` for example causes construction of `pct_string_view`. We need to revisit things like `query_rule` to see if they can store either the decoded size in the value type, or have something like this
```
struct value_type
{
    pct_string_view query;
    std::size_t parameter_count;
};
```

**Comment by alandefreitas** [comment]
All occurences of `apply_query` already receive `pct_string_view`, which already includes the decoded size, and the parameter count from `query_part_rule`.

```cpp
// [ "?" query ]
    {
        auto rv = grammar::parse(
            it, end, detail::query_part_rule);
        if(! rv)
            return rv.error();
        if(rv->has_query)
        {
            // map "?" to { {} }
            u.apply_query(
                rv->query,
                rv->count +
                    rv->query.empty());
        }
    }
```

Maybe this issue has fixed itself?

**Comment by vinniefalco** [comment]
> Maybe this issue has fixed itself?

Very possible
