### ISSUE TITLE
value construction from OptionalLike

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#531]
It should be possible to construct `param`, `param_view`, and `param_pct_view` from any _OptionalLike_

**Comment by alandefreitas** [comment]
OptionalLike doesn't exist yet. What would be the difference between OptionalLike and boost::optional?

**Comment by vinniefalco** [comment]
OptionalLike would also work with `std::optional` but as this is a feature, we should not be implementing it until Later (i.e. not Now)
