### ISSUE TITLE
Add comments to ci_equal

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/url#572]
Add comments about the expectation of forward iterators in ci_equal.

**Comment by vinniefalco** [comment]
And explore the possibility of using `size()` somehow

**Comment by alandefreitas** [comment]
> And explore the possibility of using size() somehow

I thought you didn't want that anymore. But OK. So, to be clear:

- We keep the overload string_view overload
- Make two versions of the template for size / not-size

**Comment by vinniefalco** [comment]
"explore" means we are doing design work not coding. Probably the best way to start is to ask Peter. The issue is that there is no standard concept of "range with size()" in C+11.

**Comment by alandefreitas** [comment]
True: https://en.cppreference.com/w/cpp/ranges/range

The best we have now is https://en.cppreference.com/w/cpp/ranges/size
