### ISSUE TITLE
Documentation: normalization

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/url#579]
we need a section on normalization

The ToC will look like this:

```
URLs
    Parsing
    Containers
    Segments
    Params
    Normalization
    StringToken
    Percent Encoding
```

**Comment by vinniefalco** [comment]
There's a Normalization section now but it is empty - did we have docs before? I can't find it

**Comment by alandefreitas** [comment]
No. We didn't have anything about normalization in the docs.
