### ISSUE TITLE
decoded_size

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#586]
Somehow `decoded_size` got lost in the kerfuffle. I guess because `pct_string_view` already knows it, but we still need this signature:
```
std::size_t
decoded_size( string_view s ) noexcept;
```

or perhaps this one
```
result< std::size_t >
decoded_size( string_view s ) noexcept;
```

**Comment by alandefreitas** [comment]
I think the rationale for removing the public function was that one could create a `pct_string_view` and get the decoded size.

**Comment by vinniefalco** [comment]
Yes
