### ISSUE TITLE
Unify encoding options

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/url#592]
Combine `encode_opts` and `decode_opts` into one struct

```cpp
struct encoding_opts
{
    bool space_is_plus = false;
    bool plus_is_reserved = false;
    bool lower_case = false;
    bool disallow_null = false;
    bool disallow_non_normal = false;
};
```

Otherwise, `params_ref` and `params_view` will have 2 options structs that could need setting.

This way there is only one struct, and it applies to both encoding and decoding.

The user could create and store a single option and have round trips.

**Comment by vinniefalco** [comment]
We can strike two of them and leave
```
struct encoding_opts
{
    bool space_is_plus = false;
    bool lower_case = false;
    bool disallow_null = false;
};
```
