### ISSUE TITLE
Jammyfile should set warnings

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#623]
Our Jamfile sets no warnings, so we get /W1 by default (msvc). We should crank this up. And by we I mean Alan.

**Comment by alandefreitas** [comment]
We don't set any `<warnings>` in our Jamfiles, so the default under MSVC is `/W1`. Not going to get much that way.

In `test/Jamfile`, add

```
  default-build
    <warnings>extra
```

and maybe `<warnings-as-errors>` on according to taste:

https://github.com/boostorg/variant2/blob/4d1fd43d72b6738c24e2d5f9e7438839c4bfd134/test/Jamfile#L12-L24
