### ISSUE TITLE
Outdated example in the documentation for authority_view::buffer

### ISSUE THREAD

**Issue by ea1111** [boostorg/url#663]
The [documentation for authority_view::buffer](https://www.boost.org/doc/libs/master/libs/url/doc/html/url/ref/boost__urls__authority_view/buffer.html) gives the example

`assert( parse_authority( "www.example.com" ).value().encoded_authority() == "www.example.com" );`

However, I believe this should be

`assert( parse_authority( "www.example.com" ).value().buffer() == "www.example.com" );`

since encoded_authority() was renamed to buffer().

**Comment by alandefreitas** [comment]
Thanks. You're right. It should be `buffer()`.

`encoded_authority()` still exists in `url_view` but it doesn't make sense in the `authority_view` that `parse_authority` already returns.
