### ISSUE TITLE
Sanitizers on MacOS

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/url#690]
Boostorg.core has it:

https://github.com/boostorg/core/blob/19f9aa93e1a9c76e9e5aac21c1a6f175e1583b1a/.drone.jsonnet#L337-L357

![image](https://user-images.githubusercontent.com/5369819/220418485-f2e9466d-9554-4c1f-9716-95394e7938cc.png)

but it uses a custom `macos_pipeline` instead of `osx_cxx` from `@boost_ci//ci/drone/:functions.star`.

**Comment by alandefreitas** [comment]
@sdarwin does it look like we would need to change `osx_cxx` to support macos+asan?

**Comment by alandefreitas** [comment]
This makes everything extremely easier! Thanks!

**Comment by vinniefalco** [comment]
beautiful, and this is something that is set in the framework script, right? so all projects using the new generator will get the settings
