### ISSUE TITLE
Hard to use the library for URL validation

### ISSUE THREAD

**Issue by xim** [boostorg/url#713]
I wanted to validate an externally-input URL using Boost.URL.

The naïve implementation that I assumed would be sufficient wasn't:

```cpp
auto result = boost::urls::parse_uri(url);
if (!result.has_value())
    // handle error
```
That apparently lets me parse the URL `https://` and get a result.

After that I tried
```cpp
if (!result.has_value() || !result->has_authority())
    // handle error or missing authority
```
The super-interesting is that this returns `has_authority=true`

Is this a bug, am I using the wrong API for URL validation, or do I need to use `host().empty()` instead?

Using boost 1.81.

**Comment by vinniefalco** [comment]
Can you show the string you are parsing?

**Comment by xim** [comment]
> That apparently lets me parse the URL `https://` and get a result.

Sorry, should have just put that straight in the example. I'm parsing incomplete inputs, e.g. `https://`

**Comment by vinniefalco** [comment]
That is not an incomplete input. It has an authority with a host that happens to be empty. Hosts are allowed to be empty strings.

**Comment by vinniefalco** [comment]
For example look here:
https://www.boost.org/doc/libs/master/libs/url/doc/html/url/ref/boost__urls__url_base/set_host.html#url.ref.boost__urls__url_base.set_host.bnf
![image](https://user-images.githubusercontent.com/1503976/225151336-b44e932d-1cba-48ef-8468-edc490503a62.png)

_reg-name_ is "zero or more of..." which means it can be empty. So host can be empty.

**Comment by xim** [comment]
Ah. I understand I guess it makes a world of sense for e.g. `file:///`. It is, however, not a particularly useful HTTP URL. Is there any example of using Boost.URL for more specific URL validation? Would you consider the below test somewhat solid?

```cpp
auto result = boost::urls::parse_uri(url);
if (!result.has_value() || !result->host().empty())
    // handle error or missing authority
```

**Comment by alandefreitas** [comment]
The library is correct. `https://` is a valid URL.

Have a look at the URL types: https://www.boost.org/doc/libs/master/libs/url/doc/html/url/urls/parsing.html

**Comment by vinniefalco** [comment]
Boost.URL can't know what you consider useful, you have to define that yourself. Make a formal specification of what you require to be in the URL and then use Boost.URL to check if those conditions are met. Boost.URL only guarantees that it will check whether or not the string is syntactically valid according to the ABNF grammar you choose when you select the parsing function.
