### ISSUE TITLE
parse_query does not appear in reference page

### ISSUE THREAD

**Issue by mserdarsanli** [boostorg/url#735]
It should be in functions section, next to other parse functions but is missing here
https://www.boost.org/doc/libs/1_81_0/libs/url/doc/html/url/ref.html

Below page works, but is not linked from anywhere
https://www.boost.org/doc/libs/1_81_0/libs/url/doc/html/url/ref/boost__urls__parse_query.html

**Comment by vinniefalco** [comment]
Fact Check: _true_
