### ISSUE TITLE
remove type aliases

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#743]
we should get rid of our aliases for error_code, result, et. al. and just use them directly from system.

**Comment by alandefreitas** [comment]
What happens to the headers themselves? Do we just delete `boost/url/string_view.hpp`, or leave it empty, or leave it with just `#include <boost/core/detail/string_view.hpp>`?

**Comment by alandefreitas** [comment]
Regardless of the answer to the first question, what about

```cpp
using string_view
    BOOST_DEPRECATED("Use boost::core::string_view instead") = 
        boost::core::string_view;
```

for a few versions?
