### ISSUE TITLE
vtable for urls::url not exported on mingw

### ISSUE THREAD

**Issue by mitchellwong** [boostorg/url#748]
When building under mingw, the vtable for `urls::url` isn't exported. Comparing the output of ` objdump -p libboost_url-gcc12-mt-x32-1_83.dll | grep _Z | c++filt | grep vtable` for the unmodified source vs one patched with 
```
diff --git a/include/boost/url/url.hpp b/include/boost/url/url.hpp
index 9af3592..6e99987 100644
--- a/include/boost/url/url.hpp
+++ b/include/boost/url/url.hpp
@@ -60,7 +60,7 @@ namespace urls {
         @ref parse_uri_reference,
         @ref resolve.
 */
-class BOOST_SYMBOL_VISIBLE url
+class BOOST_SYMBOL_VISIBLE BOOST_URL_DECL url
     : public url_base
 {
     friend std::hash<url>;
```
```
	4eb0c	 6354  vtable for __cxxabiv1::__class_type_info
	4eb34	 6359  vtable for __cxxabiv1::__si_class_type_info
	4eb60	 6360  vtable for __cxxabiv1::__vmi_class_type_info
	4eb8c	 6444  vtable for std::out_of_range
```
```
	4eb0c	 6354  vtable for __cxxabiv1::__class_type_info
	4eb34	 6359  vtable for __cxxabiv1::__si_class_type_info
	4eb60	 6360  vtable for __cxxabiv1::__vmi_class_type_info
	4eb8c	 6444  vtable for std::out_of_range
	[ 390] vtable for boost::urls::url
```
It appears while MSVC will export the vtable if you export all the functions of a class, gcc will only export it if you export the class itself.

**Comment by vinniefalco** [comment]
Are you proposing a fix? mingw gives me a headache

**Comment by vinniefalco** [comment]
`BOOST_URL_DECL` or `BOOST_SYMBOL_VISIBLE`? Or both?

**Comment by mitchellwong** [comment]
Visibility does nothing on Windows, but you should keep it for other platforms. Presumably there isn't a case where you would want to export on Windows but not have visibility on Linux or vice versa so you might want to just combine the macros.
