### ISSUE TITLE
drone caching failures

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/url#760]
Caching in drone job is failing when b2 updates

```
error: mismatched versions of B2 engine and core
error: B2 engine (./b2) is 4.9.6
error: B2 core (at /drone/boost-root/tools/build/src) is 4.10-git
```

**Comment by sdarwin** [comment]
https://github.com/boostorg/boost-ci/blob/master/ci/common_install.sh is purposely skipping the rebuild of b2 to save time in a caching scenario.  What could be done is add logic in that section of common_install.sh to compare b2 versions and rebuild if they are mismatched.

**Comment by sdarwin** [comment]
Pull request 213 in boostorg/boost-ci

**Comment by sdarwin** [comment]
The boost-ci PR was merged.  This issue should be fixed now.
