### ISSUE TITLE
Review integration modes in docs

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/url#780]
The docs should be updated to reflect the integration options. In particular, the "header-only" mode has been ~deprecated~ discontinued.

**Comment by mdmillerii** [comment]
Deprecated would imply it could be used but is discouraged for a new method or replacement.   The feature was ["discontinued"](https://github.com/boostorg/url/blame/1dc789839f34f9a13451c3aaa5bf4cacec04fd78/include/boost/url/src.hpp#L16) and effectively disabled, although I don't know where or how the predecessor method was implemented (I'm assuming this issue will discuss the intended replacement).

Also where is the overview maintained?  I see header-only it was removed from the 1.83 release notes [website](https://www.boost.org/doc/libs/1_83_0/libs/url/doc/html/url/overview.html)  but is still in the [adoc file](https://github.com/boostorg/url/blob/1dc789839f34f9a13451c3aaa5bf4cacec04fd78/doc/library-detail.adoc?plain=1#L109
) merged in the repository (and is still a feature of the prior 1.82 release).


https://www.merriam-webster.com/dictionary/deprecate (`3`)

https://www.oxfordlearnersdictionaries.com/definition/english/deprecate (`2`)

**Comment by alandefreitas** [comment]
Oh. That's correct.

**Comment by alandefreitas** [comment]
The documentation _was_ properly updated when 963bf5a4 was merged. I made an error.

**Comment by edtanous** [comment]
https://github.com/boostorg/url/blob/develop/README.md#header-only

develop branch still shows the docs, as does the boost-1.83.0 branch.  Where were the docs updated?

**Comment by alandefreitas** [comment]
Right. Yes. We left the README.md out. (These are not [the docs](https://www.boost.org/doc/libs/master/libs/url/doc/html/index.html) though.)

**Comment by lava** [comment]
The README on master also still mentions

> Optional header-only, without linking to a library

as one of the design goals of the library, which probably should be updated as well.
