### ISSUE TITLE
very sad - this library also not header only 

### ISSUE THREAD

**Issue by fsmoke** [boostorg/url#784]
Why again "boost" project getting various useful utility libraries, and again it's not the pure headeronly? - it's very very uncomfortable 

see my discussion json https://github.com/boostorg/json/issues/850

and boost.url has same issue - even giant libraries such as boost.asio headeronly(dll, any, polygon, geometry, format, pfr, hana, fusion, function and another dozens of boost libraries also headeronly), but not json and url - why ? This way prevent to use it inside common headers in big projects - very uncomfortable

**Comment by klemens-morgenstern** [comment]
Big projects don't do linking?

**Comment by fsmoke** [comment]
> Big projects don't do linking?

Big project - i mean project with hundreds of binaries(supprojects) in different source trees, different developers, different locations, and all of them use some common header from one common framework, this header pure header only. And if i include some inline function or class that used url or json - i will be enforced to notify all developers(because cos build of all they subprojects will be broken due undefined references) - it's not good  

and now imagine - similar common utility headers - dozens in our framework

my opinion: libraries like json and url - must be pure header only - there is many tasks parse tiny json string, or build url ....make light weight libraries like this compile dependant - is absurd

**Comment by alandefreitas** [comment]
This discussion is out of scope. General complaints about boost can go to the boost mailing list.

**Comment by vinniefalco** [comment]
> my opinion: libraries like json and url - must be pure header only

Respectfully, I disagree. I am moving away from header-only for all my libraries because they cause increased compilation times and higher maintenance costs.
