### ISSUE TITLE
Slash in query param not being encoded as %2F

### ISSUE THREAD

**Issue by msherman13** [boostorg/url#813]
Sorry if I am way off on this as far as the http spec goes but query params containing the "/" character are not being encoded as expected. In the below example, I would expect the output to be: `/?key=value1%2Fvalue2` however the output is actually `/?key=value1/value2`

```
#include <boost/url.hpp>
#include <iostream>

int main() {
	boost::urls::url url("/");
	url.params().append({"key", "value1/value2"});
	std::cout << url << std::endl;
}
```

**Comment by vinniefalco** [comment]
What makes you think these need to be escaped? They are not ambiguous, as they are not part of the target.

**Comment by alandefreitas** [comment]
To complement the answer, the only possible component after the query is a fragment. So the only delimiter after the query is a `#`. That's why `?` and `/` are allowed in the query.

**Comment by msherman13** [comment]
@vinniefalco ok makes sense. I was going off this link:

https://en.m.wikipedia.org/wiki/Percent-encoding

additionally, the AWS S3 rest API requires it:

https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

**Comment by alandefreitas** [comment]
Yes. Unreserved Characters can be used in any component, although individual components can allow more than the unreserved set. For instance:

```js
$> node
new URL('http://www.example.com/a/s/b?f=g/s')
URL {
  href: 'http://www.example.com/a/s/b?f=g/s',
  origin: 'http://www.example.com',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'www.alan.com',
  hostname: 'www.alan.com',
  port: '',
  pathname: '/a/s/b',
  search: '?f=g/s', // <--------
  searchParams: URLSearchParams { 'f' => 'g/s' },
  hash: ''
}
```

Whoever wrote the AWS tutorial got that wrong if it's meant as a requirement. I'd be surprised if the server rejects a request because a "/" in the query is unencoded.

**Comment by msherman13** [comment]
@vinniefalco its not that the AWS server rejects explicitly if slashes aren’t escaped but the issue is that the authorization signature is calculated based on what they call uri-encoded query params. So if we don’t escape the slash when calculating the signature, their signature won’t match and then they reject.

Anyway, topic for another forum. Thanks for the help
