### ISSUE TITLE
Assertion failure when iterating `params`

### ISSUE THREAD

**Issue by martinus** [boostorg/url#864]
While fuzzing a library that makes use of `boost::url` we found an assertation failure. It boils down to this reproducer:

```cpp
auto url = boost::urls::parse_relative_ref("?#");
for (auto const& param : url->params()) {
	// bang in 2nd param
}
```
This gives me an assertation fault:
```
liburlutils-test: libs/url/src/detail/params_iter_impl.cpp:72: void boost::urls::detail::params_iter_impl::setup(): Assertion `pos != ref.size()' failed.
```

Same happens btw. with `auto url = boost::urls::parse_uri("http://foo.com?#");`

**Comment by martinus** [comment]
When building with asserts disabled the code runs through, but valgrind warns about `Conditional jump or move depends on uninitialised value`

**Comment by vinniefalco** [comment]
Given `"?#"` there is one param here: `{ "", null }`. That is, an empty key with a null value.

**Comment by alandefreitas** [comment]
> Given "?#" there is one param here: { "", null }. That is, an empty key with a null value.

The issue here goes beyond that. Boost.URL is interpreting "?#" as two parameters. This one is a parsing error. The error in the implementation is related to this design choice, but it's not only about it.

**Comment by martinus** [comment]
Thanks!
