### ISSUE TITLE
master/develop docs broken

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/url#867]
These links are broken:
https://www.boost.org/doc/libs/master/libs/url/doc/html/index.html
https://www.boost.org/doc/libs/develop/libs/url/doc/html/index.html

This link no longer works
![image](https://github.com/user-attachments/assets/c3e3cbcb-f17c-4edc-bcb5-c60188870565)

**Comment by alandefreitas** [comment]
Link updated
